### PR TITLE
Add ‘GWHbranch’ to Title

### PR DESCRIPTION
**Pull request by GWHodg**
Added ‘GWHbranchDEC9 Version’ to title to test making edits > commit changes in a GitHub branch.

### CODE REVIEW

**Comment by GWHodg** [comment]
I have no idea what I am doing. Trying to submit a ‘pull request’ (whatever that is) in my ‘Spanish’ repository - just added a line under the title saying ‘GWHbranchDEC9 Version’ (or something like that.  Tried it a couple of days ago.  Looks like Eeyore replied. Should I make ANOTHER edit or should I ‘merge’ the branches.  Help me, Eeyore!

**Comment by trainee45** [comment]
Hi Elmer. I 'reviewed changes..you changed a font size from 7 to 4 and colour from silver to maroon? I think if you tap 'merge request' it makes those changes final in your original 'main' branch...or the branch that would get published? Eeyore

**Comment by GWHodg** [comment]
Hey, Eeyore - tried to enter a new edit/commit today (Sunday) w/ a new phrase re you.  Now trying to enter a ‘pull request’. Still not sure what I am doing. Let’s see if you get this. If so maybe I/we should merge this ‘branch’ to the ‘main’ & see if we can run it somehow.

**Comment by trainee45** [comment]
A pull request is an event in Git where a contributor asks a maintainer of a Git repository to review code they want to merge into a project. Watch this intermediate Git tutorial video to see how you can fork a Git repository on a remote hosting service, like GitHub.
https://www.gitkraken.com › learn
What is a Pull Request in Git? | Intermediate Git Tutorial - GitKraken
A pull request is a method of submitting contributions to an open development project. ... A pull request occurs when a developer asks for changes committed to an external repository to be considered for inclusion in a project's main repository.Nov 8, 2013
http://oss-watch.ac.uk › resources

Elmer! The above quotes might be helpful to us in understanding this stuff. Seems as though an outsider..like Eeyore (a duffus) can ask the owner of a code repository (in this case Elmer) if he can make a contribution that has been put on a newly created branch outside of the owner's main branch, if his (Eeyore's) contribution can be included in the owner's main branch. So I would assume that if Elmer was ok with Eeyore's suggested change becoming part of the 'final' code to eventually be published,then Elmer would elect to 'merge' Eeyore's branch to Elmer's main by tapping on the merge button. So if Elmer wanted to include his own suggestion, (perhaps after having asked for a review?) Elmer would tap merge to have his own suggestion included in his own main code. Of course Elmer could just add this code himself given he owns the code? Seems to me part of the confusion arises from not knowing who is being referenced in the discussions about pull requests..the owner or the collaborator. Do you think I have all this wrong? Might become clearer after I have read the tutorials as suggested above? So at any rate I would suggest Elmer go ahead and merge...seems to me Eeyore should not be allowed to do it at least not without Elmer's permission. So what confuses me is why do I (Eeyore) have the merge button available to me on your code?
Eeyore

**Comment by GWHodg** [comment]
OK - Elmer’s ‘GWHbranchDEC6’ was merged to ‘main’ & deleted.

**Pull request merged**
