### PR TITLE
reformatted some html tags

### PR DESCRIPTION
**Pull request by trainee45**
reformatted some html tags
Hi Elmer..hope you got some new golf clubs…a bit windy there today eh?! My changes were just reformating the <tr> and <td> tags in the 'eeyore is a dumb donkey row. I did this in Textastic, then created a new branch (using workingCopy) called EeyoreBranchWC, then pushed the changes to that branch in workingCopy..and voilá it appears in my github repository! So now I will create a pull request and ask you to review it..and merge pull request to main if you want? So would this be your main or just the code I cloned to my repository?

### CODE REVIEW

**Review by GWHodg — APPROVED** [review]
Reviewed @ 5:32 PM. Looks good to me.  Will try to 'merge'. Elmer

**Comment by GWHodg** [comment]
It says 'branch was merged'. I did NOT delete branch.  Will leave that for Eeyore.

**Comment by trainee45** [comment]
EeyoreBranchWC deleted @ 9:55pm

**Comment by GWHodg** [comment]
No sign of the 'dumb donkey' phrase in my (GWHodg) 'language-Spanish' repo in Textastic, Eeyore. Perhaps it is just in your cloned code.

How did you 'create the new branch' in WorkingCopy?

Weather here was OK today but expecting our first "in day" tomorrow (Tuesday) with rain & wind expected by late morning or afternoon.

How does a Zoom get-together next Sunday, Dec 19 @ 5:00 PM sound?

**Pull request merged**
