### PR TITLE
Update SPANISH.html

### PR DESCRIPTION
**Pull request by trainee45**
Added code in the Eeyore2 branch at line 333. This is a branch that replicates main but does not put the changes I added into main until it is merged (merge pull request) that becomes available after I commit this to EeyoreBranch2. Before this happens I make a pull request inviting discussion re these changes.

### CODE REVIEW

**Comment by GWHodg** [comment]
I reviewed line 333, Eeyore.  Looks good to me @ 11:32 PM Dec 12. ? Let's merge - you or me?

**Comment by trainee45** [comment]
Elmer..In the GWHodgSpanish repository I cloned from your repositories? Or I accessed directly in your repositories because we are collaborators? ..not sure how that works?..I created a new branch off your main, and called it EeyoreBranch2. This then is a replication of your code in main, and I added code at line 333 'Eeyore is a donkey with ears a meter long', and translated this to Spanish. Then I created a new pull request by tapping the Pull Request button tab in the Spanish repository showing my newly created branch..and asked for a review (by yourself). I have NOT TAPPED 'MERGE PULL REQUEST' yet as I assume one waits til the owner of the Main branch gives the ok or the owner does the merge? Not sure yet how that is supposed to work? So far the most helpful docs I have found are the ones you get right here in Github by tapping the help option in the dropdown menus under your profile name. Eeyore says Good Evening!

**Comment by GWHodg** [comment]
Got it, Eeyore.  YOU go ahead & try to 'merge' (if possible' & we'll see what happens.
BTW - I'm in the GitHub APP for some reason.

**Comment by GWHodg** [comment]
Reviewed @ 12:03 AM Dec 13.  Will try to ‘merge’!

**Comment by GWHodg** [comment]
Merge completed, apparently, Eeyore. It says “Pull request succ merged & closed - Eeyorebranch2 can be deleted”

**Comment by trainee45** [comment]
Wow..that's neat Elmer! Now how do I run the code to see what happened. Do we have to put these repositories in WorkingCopy and run via Textastic? How did you run your code..from github direct??

**Comment by trainee45** [comment]
So now its ok to delete EeyoreBranch2 right?

**Comment by trainee45** [comment]
So I will go ahead and delete the EeyoreBranch2 now.

**Comment by GWHodg** [comment]
I think so, Eeyore.

**Comment by GWHodg** [comment]
Good question re how we see/run the code. It probably has to get into WorkingCopy (where you CAN run it) somehow.

**Comment by trainee45** [comment]
I deleted my branch. How do I run the code to see what happened? Not the sign of a good programmer (me) that I make code changes without even seeing the results!!! Thats something like flying blind!!

**Comment by trainee45** [comment]
To get the code into working copy you just use 'clone repository' in Working Copy and sync the folder with Textastic. I thought we would be able to run it directly in github but I guess not?

**Comment by GWHodg** [comment]
What I just did was click "pull" in WorkingCopy & your line 333 code showed up but NOT my 'duffus' phrase.  You can run it in WC - upper R corner "HTML" box > 'preview'.

**Comment by GWHodg** [comment]
I think I may have to 'merge my GWHbranchDEC6 into main to get the 'duffus' phrase incorporated.  I'll do that (if I can).

**Comment by trainee45** [comment]
Yep that sounds right to me. I will try your 'pull' trick in working copy. Were you already in the GWHodgSpanish-language repository when you did that or does WokingCopy automatically grab any active pushes in github?

**Comment by trainee45** [comment]
HeybElmer you are becoming a real night hawk! Hope that donkey with the meter long ears is not a bad influence!

**Comment by GWHodg** [comment]
I was in the Spanish repo when I 'pulled' in WC. This stuff is addicting - should get to bed but hard to resist this stuff.

My 'dufuss' phrase DID display in WC post merge of my 'branch' - run via HTML box > 'preview' (upper R corner in WC).

Now how do I/we get all this into our Textastic code?

**Comment by trainee45** [comment]
Just saw the finished product in workingCopy using preview HTML as you indicated. Used 'pull' to update. Worked fine changes were made! To get this into textastic I think you just tap link external folder. I will have to take a closer look but seems to me it is not difficult. We made a lot of progress tonight Elmer! Hope you can get back to sleep ok after all this screen stimulation! I see all our messages are also reflected in email! Have a good night Elmer and say hi to Cathy!

**Comment by GWHodg** [comment]
Off to bed, Eeyore.  Big day tomorrow - actually leaving the 'compound' (need a new golf club).

**Comment by trainee45** [comment]
Ok Elmer. Have a good day tomorrow. Goodnight Eeyore!

**Pull request merged**
